-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "thumbnail" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "title" SET DEFAULT '',
ALTER COLUMN "body" SET DEFAULT '';
